"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."""


def sum_even_fib(max_value):
    # First two numbers in fibonacci sequence:
    a = 1
    b = 2
    result = 2  # Initial result

    for i in range(max_value):
        c = a + b
        if c > max_value:
            break

        elif c < max_value and c % 2 == 0:
            result += c

        a, b = b, c

    return result


print(sum_even_fib(4000000))

